image: golang:latest

stages:
    - build

compile:
    stage: build
    script:
      - go get gitlab.com/Ma_124/awesome-framework
      - go build gitlab.com/Ma_124/awesome-framework -o awesome
      - chmod +x awesome
      - ./awesome compile
