image: golang:latest

stages:
    - build
    - deploy

compile:
  stage: build
  script:
    - go get gitlab.com/Ma_124/awesome-framework/cmd/awesome
    - $GOPATH/bin/awesome compile --gh-max-reqs 1

pages:
  stage: deploy
  script:
  - go get gitlab.com/Ma_124/awesome-framework/cmd/awesome
  - $GOPATH/bin/awesome compile --gh-max-reqs 1
  - cp -r tmpl public
  artifacts:
    paths:
    - public
  only:
  - master

