image: golang:latest

stages:
    - build
    - deploy

compile:
  stage: build
  script:
    - echo apk add --update -t build-deps curl go git libc-dev gcc libgcc
    - go get gitlab.com/Ma_124/awesome-framework/cmd/awesome
    - $GOPATH/bin/awesome compile --gh-max-reqs 1

pages:
  stage: deploy
  script:
  - cp -r tmpl public
  artifacts:
    paths:
    - public
  only:
  - master

