language: go

go:
  - 1.x
  
sudo: false

install:
  - go get gitlab.com/Ma_124/awesome-framework/cmd/awesome

before_script:
  - $GOPATH/bin/awesome version

script:
  - AWESOME_GITHUB_MAX_REQS=1 $GOPATH/bin/awesome internal -gitlabci

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  on:
    branch: master
